todoapp/todo/urls.py
from django.urls import path

from . import views

app_name = "todo"
urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new_todo_page, name="new_todo"),
    path("add", views.add_todo, name="add_todo"),
    path("toggle-completion", views.toggle_completion, name="toggle_completion"),
    path("toggle-star", views.toggle_stars, name="toggle_stars"),
    path("new-sub-item", views.new_sub_item, name="new_sub_item"),
]

todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('',RedirectView.as_view(url='todo/',permanent=False)),
    path('admin/', admin.site.urls),
    path('todo/',include('todo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

todoapp/todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class TodoItem(models.Model):
    todo_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    status = ((0, "Incomplete"), (1, "Complete"))
    starred_choice = ((0, "Unstarred"), (1, "Starred"))
    todo_item = models.CharField(max_length=255)
    status = models.IntegerField(choices=status, default=0)
    created = models.DateTimeField("Created")
    updated = models.DateTimeField("Updated", null=True, blank=True)
    description = models.CharField("Description", max_length=255, null=True, blank=True)
    starred = models.IntegerField(choices=starred_choice, null=True, default=0, blank=True)
    deadline = models.DateTimeField("Deadline", null=True, blank=True)

    def __str__(self):
        return self.todo_item


class SubItem(models.Model):
    status = ((0, "Incomplete"), (1, "Complete"))
    todo_id = models.ForeignKey(TodoItem, on_delete=models.CASCADE)
    sub_item = models.CharField(max_length=255)
    status = models.IntegerField(choices=status, default=0)
    sub_created = models.DateTimeField("Created")
    sub_updated = models.DateTimeField("Updated", null=True, blank=True)
    sub_deadline = models.DateTimeField("Deadline", null=True, blank=True)
    sub_description = models.CharField("Description", max_length=255, null=True, blank=True)

    def __str__(self):
        return self.sub_item

todoapp/todo/forms.py
from django import forms
from .models import TodoItem, SubItem


class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ('todo_item',)

todoapp/todo/views.py
import pdb

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import TodoItem, SubItem
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .forms import TodoItemForm

# Create your views here.


@login_required
def index(request):
    form = TodoItemForm()
    todos = TodoItem.objects.prefetch_related("subitem_set").all().filter(todo_user=request.user)
    context = {"todos": todos, "form": form}
    return render(request, "todo/index.html", context=context)


@login_required
def new_todo_page(request):
    form = TodoItemForm()

    return render(request, "todo/new_todo.html", {"form": form})


@login_required
def add_todo(request):
    todo_item = request.POST["todo_item"]
    new_todo = TodoItem.objects.create(
        todo_user=request.user, todo_item=todo_item, created=timezone.now(), status=0
    )
    new_todo.save()
    context = {"todo": new_todo}
    return render(request, "todo/single_todo.html", context)


@login_required
def toggle_completion(request):
    if request.POST["type"] == "subitem":
        todo = get_object_or_404(SubItem, id=request.POST["id"])
        if not todo.todo_id.todo_user == request.user:
            return HttpResponse(status=401)
    else:
        todo = get_object_or_404(TodoItem, id=request.POST["id"])
        if not todo.todo_user_id == request.user.id:
            return HttpResponse(status=401)
    if todo:
        if todo.status == 0:
            todo.status = 1
        else:
            todo.status = 0
        todo.save()
        return HttpResponse(status=200)


@login_required
def toggle_stars(request):
    todo = get_object_or_404(TodoItem, id=request.POST["id"])
    if not todo.todo_user_id == request.user.id:
        return HttpResponse(status=401)
    if todo:
        if todo.starred == 0:
            todo.starred = 1
        else:
            todo.starred = 0
        todo.save()
        return HttpResponse(status=200)


@login_required
def new_sub_item(request):
    id = request.POST["todo_item_id"]
    id = id.split("_")[-1]
    todo = get_object_or_404(TodoItem, id=id, todo_user=request.user)
    sub_item = todo.subitem_set.create(
        sub_item=request.POST["sub_item"], sub_created=timezone.now()
    )
    print(sub_item)
    context = {"subitem": sub_item}
    return render(request, "todo/single_sub_item.html", context)
    # return HttpResponse(status=200)

todoapp/todo/templates/todo/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en" class="dark-theme">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.css.map"> -->
    <link rel="stylesheet" href="{% static 'css/todo.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}" />

</head>
<body>
    <div class="section">
        <div class="night-mode-toggle ">
            <i class="fas fa-circle  fa-2x"></i>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
<script
              src="https://code.jquery.com/jquery-3.3.1.min.js"
              integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
              crossorigin="anonymous">
</script>
<script src="{% static 'js/todo.js' %}"></script>
<link href="https://fonts.googleapis.com/css?family=Libre+Franklin" rel="stylesheet">
</html>

todoapp/todo/templates/todo/index.html
<!-- TODO Fix duplicate ids replace id with data-attributes -->
{% extends "todo/base.html" %}
{% load todo_templates %}
{% block content %}

<h1 class="title">TaskBook</h1>

<a href="{% url 'todo:new_todo' %}" id="new_todo_link">
    <i class="fas fa-plus"></i>
    New Todo (n)
</a>

{% csrf_token %}

<ul class="none-list-type" id="parent_list">
    {% for todo in todos %}
    <li id="{{todo.id}}">
        <section class="todo-item">

            {% if todo.starred == 0 %}
                <span class="icon has-text-grey star-toggle" data-todoid="{{todo.id}}">
            {% else %}
                <span class="icon has-text-warning star-toggle" data-todoid="{{todo.id}}">
            {% endif %}
                    <i class="fas fa-star"></i>
                </span>
            <span class="board">{{ todo.todo_item }}</span>

            <ol class="sub-item">
                {% if todo.subitem_set.all %}
                {% for subitem in todo.subitem_set.all %}
                {% if subitem.status == 0 %}
                    <li>
                        <input type="checkbox" name="{{ subitem.id }}" id="subitem_{{ subitem.id }}" class="completed-checkbox subitem-checkbox">
                {% else %}
                    <li class="task-completed">
                        <input type="checkbox" name="{{ subitem.id }}" id="subitem_{{ subitem.id }}" class="completed-checkbox subitem-checkbox" checked>
                {% endif %}
                    <span>{{ subitem.sub_item }}</span>
                    <span class="relative-date">{{ subitem.sub_created|custom_timestamp }}</span>
                </li>
                {% endfor %}

                {% endif %}
            </ol>
                <a class="new-sub-item" data-todoid="{{todo.id}}" id="todo_{{todo.id}}">
                    <i class="fas fa-plus"></i>
                    Add New
                </a>
        </section>
    </li>

    {% endfor %}
</ul>

<div class="modal" id="new_todo_modal">
    <div class="modal-background"></div>
    <div class="modal-content">
        <div class="box">
            <h1>Add new todo</h1>
            <form id="new_todo_form" action="{% url 'todo:add_todo' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-default">Save</button>
            </form>
        </div>

    </div>
    <button class="modal-close is-large" aria-label="close"></button>
</div>

{% endblock %}

todoapp/todo/templates/todo/new_todo.html
{% extends "todo/base.html" %}

{% block content %}

<h1>Add new todo</h1>
<form action="{% url 'todo:add_todo' %}" method="POST" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>    
</form>

{% endblock %}

todoapp/todo/templates/todo/single_sub_item.html
{% load todo_templates %}

{% if subitem.status == 0 %}
<li>
    <input type="checkbox" name="{{ subitem.id }}" id="subitem_{{ subitem.id }}" class="completed-checkbox subitem-checkbox">
    {% else %}
<li class="task-completed">
    <input type="checkbox" name="{{ subitem.id }}" id="subitem_{{ subitem.id }}" class="completed-checkbox subitem-checkbox"
        checked>
    {% endif %}
    <span>{{ subitem.sub_item }}</span>
    <span class="relative-date">{{ subitem.sub_created|custom_timestamp }}</span>
</li>

todoapp/todo/templates/todo/single_todo.html
<li id="{{todo.id}}">
    <section class="todo-item">
        {% if todo.starred == 0 %}
        <span class="icon has-text-grey star-toggle" data-todoid="{{todo.id}}">
            {% else %}
            <span class="icon has-text-warning star-toggle" data-todoid="{{todo.id}}">
                {% endif %}
                <i class="fas fa-star"></i>
            </span>
            <span class="board">{{ todo.todo_item }}</span>

            <ol class="sub-item">

            </ol>
            <a class="new-sub-item" data-todoid="{{todo.id}}" id="todo_{{todo.id}}">
                <i class="fas fa-plus"></i>
                Add New
            </a>
    </section>
</li>